# IronWall v1.26.0 - 端口扫描检测监狱（全端口封禁）
# 安装位置：/etc/fail2ban/jail.d/ironwall-portscan.conf

[ironwall-portscan]
ignoreip  = 127.0.0.1/8 ::1 203.0.113.10 203.0.113.11
enabled   = true
port      = all
filter    = ironwall-portscan
logpath   = /www/wwwroot/jdy-cloud/logs/ironwall-portscan.log
maxretry  = 1
findtime  = 600
bantime   = 1800
bantime.increment = true
bantime.factor    = 2
bantime.maxtime   = 604800
banaction = iptables-allports
action    = %(action_)s